### ISSUE TITLE
Django 5 support

### ISSUE THREAD

**Issue by Alzavio** [pkavumba/django-vectordb#15]
Hi, I've tried installing on Django 5, which Django VectorDB doesn't yet support to see if it'd work, and as expected, ran into an error. Just curious to know roughly when or if Django 5 support is expected.  Also, curious to know where vectordb.0001_initial is or how I could reset this since I'm still getting the error after rolling back...

Environment: Python 3.11, Windows 11, Django 5

Error running migrations:
  Applying vectordb.0001_initial...Traceback (most recent call last):
  File "C:\Users\...\anaconda3\envs\studypt\Lib\site-packages\django\db\backends\utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "django_content_type"

**Comment by pkavumba** [comment]
Thanks for reporting the issue. Will try to get it running within this week or latest next week
