### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by GildasLepennetier** [pkavumba/django-vectordb#17]
Hi there,
I do not manage to get a score after the results are returned

In the view.py, I have the search part:
```
matched_data = vectordb.search(search_data)
```

I pass the variable, then iterate to print the data. In the template, the code is:

```
{% for item in matched_data %}
<tr><td>{{ item.score }}</td></tr>
{% endfor %}
```
But nothing is displayed.
Any hint welcome!

**Comment by pkavumba** [comment]
Hi! The distance between the query and the results is named as `distance`. You will need to use `{{ item.distance }}`

**Comment by GildasLepennetier** [comment]
Thanks for your answer!
Then allow me to create the request, I think the documentation was unclear:
see: [/pull/18](https://github.com/pkavumba/django-vectordb/pull/18)

**Comment by pkavumba** [comment]
Thanks for raising it. I have seen the PR. I will merge it soon
