### ISSUE TITLE
What happens if you edit the metadata after you've saved an instance?

### ISSUE THREAD

**Issue by LukasNelNexUnicorn** [pkavumba/django-vectordb#2]
I forgot to add some important fields to my metadata, but when I tried to readd the instance to show the new metadata, it gave me a "unique constraint violated" error
![image](https://github.com/pkavumba/django-vectordb/assets/118032092/8b85fb94-33fd-4c55-bbe7-8e60802070fc)
Is there a way around this to manually update previously added instances to show the new metadata?

**Comment by pkavumba** [comment]
Hello! Thank you for bringing up this issue. To conveniently update the metadata, you can execute the sync command as follows:

```
./manage.py vectordb_sync <app_name> <model_name>
```

This command will not only refresh the metadata but also synchronize all vectors if there have been any changes in the text representation. Please make sure you have the most recent version of `vectordb` installed.

To further enhance the functionality, I'll be working on incorporating a method for manually updating the `vectordb`. Stay tuned for updates!
