### ISSUE TITLE
Thank you for your project

### ISSUE THREAD

**Issue by Drzhivago264** [pkavumba/django-vectordb#20]
Thank you for offering such a great convenient.
It is must be great to benchmark it against pg_vector.

1. Beside the convenient of plugging this on any sql server, can you please explain the trade-off between embedding and searching by Django vs deloading them to a standalone solution such as postgres.
2. This solution will not work in celery workers without --pool solo or --pool threads. Pytorch complains when it tries to fork more thread. How should I deal with this?

**Comment by pkavumba** [comment]
Hi @Drzhivago264!
## 1. Regarding trade-offs:
1. `django-vectordb`:
- It is very fast and accurate --- there is no trade-off of accuracy for small Django models.
- seamless integration within the Django environment. 
- It automatically synchronizes your embeddings whenever there are Create, Delete, and Update operations on the underlying data. 
- This integration allows you to continuously use Django's querysets

2. PostgreSQL with `pg_vector` 
- You are locked in and it can be expensive to migrate DBs if your application is not using PostgreSQL in the first place
- You have to setup your own synchronization API

## 2. Celery 
- I am looking into that case. I hadn't considered it earlier. I will try to push a solution as soon as possible

**Comment by Drzhivago264** [comment]
Hello,
I have read around for a bit and it seems that the vector need to get index in ram,
If I have multiple web server with 1 sql server, then it will make more sense to have a lot of ram on the sql server rather than a bunch of large web server with duplicated graph index.

If I stay with this solution I will need to host django on the sql server and open endpoint to it so other webserver can query the django server on the sql node. Do I misunderstood anything?

**Comment by pkavumba** [comment]
You are right, the vectordb is indexed in memory, so having a lot of RAM on the SQL server would be beneficial. However, we make some optimizations:
- If the database has less than 10K objects, no index is created ahead of time to save memory.
- If you are filtering the data and the number of candidate objects is below 10K, a single-use index is created, and a greedy search is performed, as it is more accurate and quite efficient to build at such sizes

**Comment by Drzhivago264** [comment]
Thank you
