### ISSUE TITLE
OpenAIEmbeddings : AttributeError: 'list' object has no attribute 'astype'

### ISSUE THREAD

**Issue by Fl0r14n** [pkavumba/django-vectordb#7]
settings: 

DJANGO_VECTOR_DB = {
    'DEFAULT_EMBEDDING_CLASS': 'vectordb.embedding_functions.OpenAIEmbeddings',
    'DEFAULT_EMBEDDING_MODEL': 'text-embedding-ada-002',
    'DEFAULT_EMBEDDING_SPACE': 'cosine',
    'DEFAULT_EMBEDDING_DIMENSION': 1536,
....
}

error:

/site-packages/vectordb/manager.py", line 77, in add_instance
    return create_vector_from_instance(manager=self, instance=instance)

/site-packages/vectordb/utils.py", line 77, in create_vector_from_instance
    embedding=embedding.astype("float32").tobytes(),
              ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'astype'

the embedding vector is returned and is indeed a list with values from 0-1 but not an array object like in the case of sentence-transformers

**Comment by pkavumba** [comment]
Thanks for raising the issue. It has been fix #9
